apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: tNAMAMI95vbl1efp
kind: ConfigMap
metadata:
  name: jarvis-mysql-config
  namespace: ai-platform
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jarvis-mysql
  name: jarvis-mysql
  namespace: ai-platform
spec:
  ports:
  - port: 3306
    targetPort: mysqld
  selector:
    app: jarvis-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jarvis-mysql-pvc
  name: jarvis-mysql-pvc
  namespace: ai-platform
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jarvis-mysql
  name: jarvis-mysql
  namespace: ai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jarvis-mysql
  template:
    metadata:
      labels:
        app: jarvis-mysql
      name: jarvis-mysql
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        - --sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
        envFrom:
        - configMapRef:
            name: jarvis-mysql-config
        image: registry.effyic.com/library/mysql:8.0
        imagePullPolicy: IfNotPresent
        name: jarvis-mysql
        ports:
        - containerPort: 3306
          name: mysqld
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: jarvis-mysql-data
      restartPolicy: Always
      volumes:
      - name: jarvis-mysql-data
        persistentVolumeClaim:
          claimName: jarvis-mysql-pvc
